server:
  port: 80
zuul:
  routes:
    account: /api/account/**
    config: /api/config/**
  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
    semaphore:
      max-semaphores: 200
  ignored-patterns:
    - /admin
    - /myadmin
ribbon:
  ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
gateway:
  devMode: true
  tokenCode: Authorization
  timestampCode: timestamp
  signatureCode: signature
  nonceCode: nonce
  ignore:
    - /api/account/signin
    - /api/account/signup
    - /api/account/signout
    - /api/account/secretkey
    - /api/account/resetpassword
spring:
  datasource:
    url: jdbc:mysql://localhost/cloud?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver