server:
  port: 80
zuul:
  routes:
    accountService:
      path: /api/account/**
      service-id: account
      sensitiveHeaders:
  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
    semaphore:
      max-semaphores: 200
  ignored-patterns:
    - /admin
    - /myadmin
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
gateway:
  devMode: true
  tokenCode: Authorization
  timestampCode: timestamp
  signatureCode: signature
  nonceCode: nonce
  ignore:
    - /api/account/auth/signin
    - /api/account/auth/signup
    - /api/account/auth/signout
    - /api/account/auth/resetpassword
spring:
  datasource:
    url: jdbc:mysql://localhost/cloud?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver